### ISSUE TITLE
Please include latest PapApi.class.php

### ISSUE THREAD

**Issue by brooksy4503** [strangerstudios/pmpro-post-affiliate-pro#8]
Hi,

Website fails to load until I replaced with latest PapApi.class.php

Could you please include the latest api in this plugin.

Thanks

Garth

**Comment by kimcoleman** [comment]
The PR for the updated API is in and we will be testing it. If you would like to try the new code as well it is available in this PR: https://github.com/strangerstudios/pmpro-post-affiliate-pro/pull/10
